accounts/urls.py
from django.urls import path, include
from . import views
app_name = "accounts"
urlpatterns = [path("", include("django.contrib.auth.urls")),
               path("register/", views.register, name="register")
               ]

bookly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bookly_nest.urls")),
    path("accounts/", include("accounts.urls")),
]

bookly_nest/urls.py
from django.urls import path
from . import views

app_name = "bookly_nest"
urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    path("genres/", views.genres, name="genres"),
    path("genres/<int:genre_id>", views.genre, name="genre"),
    path("new_genre/", views.new_genre, name="new_genre"),
    path("new_book/<int:genre_id>", views.new_book, name="new_book"),
    path("edit_book/<int:book_id>", views.edit_book, name="edit_book"),
    path("delete_book/<int:book_id>", views.delete_book, name="delete_book"),
]

accounts/models.py
from django.db import models

# Create your models here.

bookly_nest/models.py
from django.db import models
from django.contrib.auth.models import User


class Genre(models.Model):
    name = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Book(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    published_year = models.IntegerField()
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Book"
        verbose_name_plural = "Books"

    def __str__(self) -> str:
        return self.title

bookly_nest/forms.py
from django import forms

from .models import Genre, Book


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ["name"]
        labels = {"name": ""}


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["title", "author", "published_year", "description"]
        labels = {
            "title": "Title",
            "author": "Author",
            "published_year": "Year Published",
            "description": "Description",
        }
        widgets = {"description": forms.Textarea(attrs={"cols": 80})}

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


# Create your views here.
def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log the new user in
            login(request, new_user)
            return redirect("bookly_nest:index")
    context = {"form": form}
    return render(request, "registration/register.html", context)

bookly_nest/views.py
from django.http import Http404
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from .forms import GenreForm, BookForm


from .models import Book, Genre


# Create your views here.
def index(request):
    books = Book.objects.all()

    context = {"books": books}
    return render(request, "bookly_nest/index.html", context)


@login_required
def genres(request):
    # genres = Genre.objects.all()
    genres = Genre.objects.filter(owner=request.user)
    context = {"genres": genres}
    return render(request, "bookly_nest/genres.html", context)


@login_required
def genre(request, genre_id):
    genre = Genre.objects.get(id=genre_id)

    if genre.owner != request.user:
        raise Http404
    books = genre.book_set.order_by("-date_added")

    context = {"genre": genre, "books": books}

    return render(request, "bookly_nest/genre.html", context)


@login_required
def new_genre(request):
    if request.method != "POST":
        # No data submitted; create a blank form
        form = GenreForm()
    else:
        # POST data submitted; process data
        form = GenreForm(data=request.POST)

        if form.is_valid():
            # save the form data
            # associate the genre with the current user
            new_genre = form.save(commit=False)
            new_genre.owner = request.user
            new_genre.save()
            return redirect("bookly_nest:genres")

    context = {"form": form}
    return render(request, "bookly_nest/new_genre.html", context)


@login_required
def new_book(request, genre_id):
    genre = Genre.objects.get(id=genre_id)

    if request.method != "POST":
        form = BookForm()

    else:
        form = BookForm(data=request.POST)
        if form.is_valid():
            new_book = form.save(commit=False)
            new_book.genre = genre  # Important - genre-book association!
            new_book.save()

            return redirect("bookly_nest:genre", genre_id=genre_id)
    context = {"genre": genre, "form": form}
    return render(request, "bookly_nest/new_book.html", context)


@login_required
def edit_book(request, book_id):
    book = Book.objects.get(id=book_id)
    genre = book.genre

    if genre.owner != request.user:
        raise Http404

    if request.method != "POST":
        # prefill the form with the current book data
        form = BookForm(instance=book)
    else:
        form = BookForm(instance=book, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("bookly_nest:genre", genre_id=genre.id)

    context = {"book": book, "genre": genre, "form": form}
    return render(request, "bookly_nest/edit_book.html", context)


def delete_book(request, book_id):
    book = Book.objects.get(id=book_id)
    genre = book.genre

    if genre.owner != request.user:
        raise Http404
    if request.method == "POST":
        book.delete()
        return redirect("bookly_nest:genre", genre_id=genre.id)
    elif request.method == "GET":
        context = {"genre": genre, "book": book}
        return render(request, "bookly_nest/delete_book.html", context)

bookly_nest/templates/bookly_nest/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BooklyNest</title>
        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url "bookly_nest:index" %}">BooklyNest</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNav"
                        aria-controls="navbarCollapse"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link"  href="{% url "bookly_nest:genres" %}">Genres</a>
                        </li>
                    </ul>
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                        <!-- Authentication Links -->
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <span class="nav-text me-2">Welcome, {{ user.username }}</span>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "accounts:register" %}">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                    <!-- End of account related links -->
                    {% if user.is_authenticated %}
                        <form action="{% url 'accounts:logout' %}" method='post'>
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-secondary btn-sm">Logout</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>
        <!-- End of Navbar -->
        <main class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}
                {% endblock page_header %}
            </div>
            <div>
                {% block content %}
                {% endblock content %}
            </div>
        </main>
    </body>
</html>
{% comment %} <a href="{% url "bookly_nest:index" %}">BooklyNest</a> -
<a href="{% url "bookly_nest:genres" %}">Genre</a>
{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}.</p>
{% else %}
    <a href="{% url "accounts:login" %}">Login</a> -
    <a class="nav-link" href="{% url "accounts:register" %}">Register</a>
{% endif %}
{% block content %}
{% endblock content %}
{% if user.is_authenticated %}
    <hr />
    <form action="{% url "accounts:logout" %}" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endif %} {% endcomment %}

bookly_nest/templates/bookly_nest/delete_book.html
{% extends "bookly_nest/base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h2>Delete Book</h2>
{% endblock page_header %}
{% block content %}
    <form method="post">
        {{ form.as_div }}
        <p>Are you sure you want to delete: "{{ book.title }} "?</p>
        {% csrf_token %}
        {% bootstrap_button button_type="submit" content="Yes Delete" %}
        <a class="p-2 g-col-6" href="{% url 'bookly_nest:genre' genre.id %}">Cancel</a>
    </form>
{% endblock content %}

bookly_nest/templates/bookly_nest/edit_book.html
{% extends "bookly_nest/base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h2>Edit Book</h2>
{% endblock page_header %}
{% block content %}
    <a href="{% url "bookly_nest:genre" genre.id %}">{{ genre }}</a>
    <form {% url "bookly_nest:edit_book" book.id %} method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Save changes" %}
        {% comment %} {{ form.as_div }}
        <button type="submit">Save changes</button> {% endcomment %}
    </form>
{% endblock content %}

bookly_nest/templates/bookly_nest/genre.html
{% extends "bookly_nest/base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <p>Genre: {{ genre }}</p>
{% endblock page_header %}
{% block content %}
    <a href="{% url "bookly_nest:new_book" genre.id %}">Add a new book</a>
    <ul>
        {% for book in books %}
            <div class="card mb-3">
                <h6 class="card-header">
                    Added:  {{ book.date_added|date:"M d, Y H:i" }}
                    <small><a href="{% url 'bookly_nest:edit_book' book.id %}">Edit book</a></small>
                </h6>
                <p>Title: {{ book.title }}</p>
                <p>Author: {{ book.author }}</p>
                <div class="card-body">
                    <p>Description:</p>
                    {{ book.description }}
                </div>
                <small>
                    <a class="text-danger"
                       href="{% url 'bookly_nest:delete_book' book.id %}">Delete book</a>
                </small>
            </div>
        {% empty %}
            <p>No books found.</p>
        {% endfor %}
    </ul>
{% endblock content %}

bookly_nest/templates/bookly_nest/genres.html
{% extends "bookly_nest/base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h1>Genres</h1>
{% endblock page_header %}
{% block content %}
    <ul class="list-group list-inline">
        {% for genre in genres %}
            <li>
                <a class="list-group-item list-group-item-active"
                   href="{% url "bookly_nest:genre" genre.id %}">{{ genre.name }}</a>
            </li>
        {% empty %}
            <p>No genres have been added.</p>
        {% endfor %}
    </ul>
    <div class="mt-4">
        <a href="{% url "bookly_nest:new_genre" %}">Add a new genre</a>
    </div>
{% endblock content %}

bookly_nest/templates/bookly_nest/index.html
{% extends "bookly_nest/base.html" %}
{% block content %}
    <div class="container">
        <div class="col-md-12">
            <h1 class="display-2">Bookly Nest</h1>
            <p class="lead">
                Welcome to Bookly Nest, a place to manage your book library.
                Whenever you find a book, you can add it to your library and keep track of it.
                You can also add a review/notes to the book.
            </p>
        </div>
        <a class="btn btn-primary btn-lg mt-1 bg-primary"
           href="{% url "accounts:register" %}">Register &raquo;</a>
    </div>
{% endblock content %}

bookly_nest/templates/bookly_nest/new_book.html
{% extends "bookly_nest/base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h2>Add new book</h2>
{% endblock page_header %}
{% block content %}
    <a href="{% url "bookly_nest:genre" genre.id %}">Genre: {{ genre }}</a>
    <form {% url "bookly_nest:new_book" genre.id %} method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add new book" %}
        {% comment %} {{ form.as_div }}
        <button type="submit">Add new book</button> {% endcomment %}
    </form>
{% endblock content %}

bookly_nest/templates/bookly_nest/new_genre.html
{% extends "bookly_nest/base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h2>Add new genre</h2>
{% endblock page_header %}
{% block content %}
    <form {% url "bookly_nest:new_genre" %} method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add genre" %}
        {% comment %} {{ form.as_div }}
        <button type="submit">Add genre</button> {% endcomment %}
    </form>
{% endblock content %}